---
title: "R Notebook"
output: html_notebook
---


```{r}
library(corrplot)
library(RColorBrewer)
library(reshape2)
library(ggplot2)
library(gridExtra)
library(ggpubr)
library(CytoTree)
library(flowCore)
library(stringr)
library("dplyr")
theme_set(theme_pubr())
library(FlowSOM)
library(circlize)
library(ComplexHeatmap)


source("D:/users/fperez/NKI_TMAs_AF/devNKI-scripts/3_Cell-typeClassification/qc_functions.R")
source("D:/users/fperez/NKI_TMAs_AF/devNKI-scripts/3_Cell-typeClassification/cell_type_caller_functions.R")

project.path <- "D:/users/fperez/NKI_TMAs_AF/"
outout.folder.name <- "D:/users/fperez/NKI_TMAs_AF/Analysis_results/02_MetaClusters_Zscore2/"
tribus.subfolder <- "Tribus_Cell-segment_202304"
celltypes.file.suffix = "_cellTypes.csv"
```
#Reading clinical info

```{r}
cycif2samples <- read.table(file="D:/users/fperez/NKI_TMAs_AF/devNKI-scripts/3_Cell-typeClassification/tCicyf_patients-cores_pass.csv", sep=",", header = TRUE)
clinical.info <- read.table(file="D:/users/fperez/NKI_TMAs_AF/Clinical_data/T-CycIF.csv", sep=",", header = TRUE)

clin.columns.interest <- c("TnumberAVL","CFsample","centre","incyear","figo_stage",
                           "Molecular_profile","therapy_sequence")

clinical.info <- clinical.info[,clin.columns.interest]

clin.tcycif <- merge(cycif2samples, clinical.info, by.x="patient", by.y="TnumberAVL")
```



#Reading input tCycif data and cell.type data
```{r}
#List all the tables with celltype labels
big.data.set <- NULL
files <- list.files(path=project.path, pattern = "TMA_", full.names = T)
#Read all cell.type and signal intensity data
for (f in files){
  cycif.slide <- basename(f)
  slide.data <- read.table(file=paste0(f, "/", tribus.subfolder, "/", cycif.slide, celltypes.file.suffix), sep=",", header=TRUE)
  slide.data <- cbind(cycif.slide, slide.data)
  slide.data$Row_number <- paste0(cycif.slide,":",slide.data$Row_number)
  colnames(slide.data)[colnames(slide.data) == "CoreId"] <- "cycif.core.id"
  slide.data$cycif.core.id <- paste0("core",slide.data$cycif.core.id)
  big.data.set <- rbind(big.data.set,slide.data)
}
```


#QC and filtering of the cell.type dataset
```{r}
#Performing QC according to cell.types
#Ignoring cell with low DAPI intensity and out of the core
big.data.set <- big.data.set %>% dplyr::filter(GlobalCellType != "LowDapi")

#Ignoring non-useful columns
#big.data.set <- big.data.set %>% select(-out_of_core, -lost, -Inside_ROI)


dat.immune <- big.data.set %>%
                  dplyr::filter(GlobalCellType != "Cancer",
                                GlobalCellType != "Stromal",
                                GlobalCellType != "Others")
dat.cancer <- big.data.set %>% dplyr::filter(GlobalCellType == "Cancer")
dat.stromal <- big.data.set[grep("Stromal", big.data.set$GlobalCellType),]
```


```{r}
#Functions to be used for the metaclustering of cancer and stromal cells

#Function to scale the dataset
scale.dataset <- function(dataset, channels, last.antibody.channel=11, norm.by=NA, min.max=TRUE){
  if (!is.na(norm.by)){
    table.scaled <- NULL
    for (i in unique(dataset[,norm.by])){
      data.subset <- dataset[dataset[,norm.by] %in% i,channels]
      #Log2 for antibody intensity channels
      table.dat  <- log2(data.subset[,1:last.antibody.channel]) 
      #Truncating intensity data to 0.99 percentile only the channels
      trimmed.list <- z.trimming(table.dat, max.quantile=0.99, min.quantile=0.001) 
      table.dat.trim <- trimmed.list[[1]]
      #Truncating morphology data to 0.999
      morphology.dat <- data.subset[,(last.antibody.channel+1):length(channels)]
      trimmed.list <- z.trimming(morphology.dat, max.quantile=0.999) 
      morphology.dat.trim <- trimmed.list[[1]]
      #Rest of the columns correspond to morphology features, not log2 for them
      mat.dat = cbind(table.dat.trim, morphology.dat.trim) 
      table.scaled.set <- scale(mat.dat) #Z-score normalization
      if(min.max){
        table.scaled.set <- apply(table.scaled.set,2,min_max_norm) #Min.Max normalization
      }
      table.scaled <- rbind(table.scaled, table.scaled.set)
    }
  }else{
    table <- dataset[,channels]
    table.dat  <- log2(table[,1:last.antibody.channel])
    table = cbind(table.dat, table[,(last.antibody.channel+1):length(channels)])
    data.filtered.trim <- z.trimming(table)
    mat.dat <- data.filtered.trim[[1]]
    table.scaled <- scale(mat.dat)
    if(min.max){
      table.scaled <- apply(table.scaled,2,min_max_norm) #Min.Max normalization
    }
  }
  return(table.scaled)
}

#Running FloWSOM and 
som.metaclustering.consensus <- function(dataset, kval=10, tempdir){
out.som <- FlowSOM::ReadInput(dataset, transform = FALSE, scale = FALSE)
out.som <- FlowSOM::BuildSOM(out.som, colsToUse = colnames(dataset), silent=T, xdim=80, ydim=80)
out.som <- FlowSOM::BuildMST(out.som, silent=T)
out.results <- suppressMessages(ConsensusClusterPlus::ConsensusClusterPlus(t(out.som$map$codes),
        maxK = 15, reps = 300, pItem = 0.9, pFeature = 1, title = tempdir, 
        plot = "png", verbose = FALSE, clusterAlg = "hc", 
        distance = "euclidean", seed = 10))
metaclusters <- out.results[[kval]]$consensusClass
return(metaclusters[out.som$map$mapping[,1]])
}
```


```{r}
###############Metaclustering of the cells###########

#Channels used for the metaclustering
interesting.channels.stromal <- c("pTBK1","Ki67","Vimentin", "pSTAT1", "MHCI",
                      "ECadherin","aSMA","CD31","PDL1_488","Area","Eccentricity","Roundness")

interesting.channels.cancer <- c("Ki67","Vimentin","pSTAT1", "MHCI", "ECadherin","yH2AX",
                                 "pTBK1", "cPARP1", "CK7","PDL1_488","Area",
                                 "Eccentricity", "Roundness")


#Scaling datasets
mat.stromal <- scale.dataset(dat.stromal, interesting.channels.stromal,
                             last.antibody.channel = 9, norm.by = "cycif.slide")
  
mat.cancer <- scale.dataset(dat.cancer, interesting.channels.cancer,
                             last.antibody.channel = 10, norm.by = "cycif.slide")

#Directories where to store the consensus clustering plots of the SOM nodes
tmpdir.cancer <- "D:/users/fperez/NKI_TMAs_AF/Cell_class_analysis/SOM_consensusClusters_cancer_Slide-scaled3/"
tmpdir.stromal <- "D:/users/fperez/NKI_TMAs_AF/Cell_class_analysis/SOM_consensusClusters_stromal_Slide-scaled3/"

metalabels.cancer <- som.metaclustering.consensus(mat.cancer, kval = 8,
                                                  tmpdir.cancer)
metalabels.stromal <- som.metaclustering.consensus(mat.stromal, kval = 8,
                                                   tmpdir.stromal)



```



```{r}
#A big function to plot UMAPs, downscaling dataset
#Extralabels should be a list of vectors
channel.UMAPs <- function(df, cell.labels, extralabels=NULL, rowselectionstatus=NULL,
                          sub.sample=FALSE,
                          n.sampling=10000, user.colors=mycolors, umap_neighbors=30, umap_mindist=0.30){
  if (!is.null(rowselectionstatus)){
    df <- df[rowselectionstatus,]
  }
  
  if (sub.sample){
    sampling.rows <- sample(1:nrow(df), n.sampling)
    df <- df[sampling.rows,]
    cell.labels <- cell.labels[sampling.rows]
    if (!is.null(extralabels)){
      for (i in 1:length(extralabels)){
        extralabels[[i]] <- extralabels[[i]][sampling.rows]
      }
    }
  }
  
  umap_s = uwot::umap(df, n_neighbors = umap_neighbors, scale=FALSE, spread=1.5,
                      min_dist = umap_mindist, n_epochs = 60)
  
  uplot = data.frame(x = umap_s[,1], y= umap_s[,2])
  pltChannels <- list()
  pltChannels <- lapply(1:ncol(df), function(x){
    markers <- df[, x]
    p = ggplot(data=uplot,aes(x,y, color=markers)) + geom_point(size=0.3, stroke=0, alpha=0.7)+ 
      #guides(color = guide_legend(override.aes = list(size=5))) + 
      theme_bw() + coord_fixed(ratio=1)+ 
      xlab("umap1") + ylab("umap2") + theme(legend.position="none") + theme(aspect.ratio=1) +
      scale_colour_gradient(low = "#103254", high="green")
    p <- p + ggtitle(colnames(df)[x])
    return(p)
  })
  
  Subtype <- factor(cell.labels, levels=unique(cell.labels))
  #df <- cbind(df$Subtype)
  
  pl = ggplot(uplot,aes(x,y, color=Subtype))+ geom_point(size=0.4, stroke=0, alpha=0.7)+ 
    geom_density_2d(color="grey60", alpha=0.6) +
    scale_fill_viridis(discrete = TRUE) + 
    guides(color = guide_legend(override.aes = list(size=10))) + 
    scale_color_manual(values=user.colors) + theme_bw() + coord_fixed(ratio=1)+
    guides(colour = guide_legend(override.aes = list(size=10, shape=15, alpha=1), direction="horizontal", ncol=2, label.position="bottom", byrow=F)) + 
    xlab("umap1") + ylab("umap2") + #ylim(-10, 10) + 
    theme(legend.title = element_blank(), aspect.ratio=1.1)
  
  plots = list(pltChannels,pl)
  
  if(!is.null(extralabels)){
    pltExtras <- lapply(1:length(extralabels), function(x){
      extralabel <- factor(extralabels[[x]], levels=unique(extralabels[[x]]))
      px = ggplot(uplot,aes(x,y, color=extralabel))+ geom_point(size=0.4, stroke=0, alpha=0.7)+ 
          geom_density_2d(color="grey60", alpha=0.6) +
          scale_fill_viridis(discrete = TRUE) + 
          guides(color = guide_legend(override.aes = list(size=10))) + 
          scale_color_manual(values=user.colors) + theme_bw() + coord_fixed(ratio=1)+
          guides(colour = guide_legend(override.aes = list(size=10, shape=15, alpha=1),
          direction="horizontal", ncol=2, label.position="bottom", byrow=F)) + 
          xlab("umap1") + ylab("umap2") + #ylim(-10, 10) + 
          theme(legend.title = element_blank(), aspect.ratio=1.1)
      return(px)
  })
  }
  plots = append(plots,pltExtras)
  return(plots)
}

```



#Exploring metaclusters
```{r}
dir.create(outout.folder.name)

#Scaling datasets
Metacluster.ID <- paste0("Cluster",metalabels.cancer)
mat.cancer2 <- cbind(dat.cancer, Metacluster.ID)

Metacluster.ID <- paste0("Cluster",metalabels.stromal)
mat.stromal2 <- cbind(dat.stromal, Metacluster.ID)

dat.cancer.clin2 <- merge(mat.cancer2, clin.tcycif, by = c("cycif.slide", "cycif.core.id")) 
dat.stromal.clin2 <- merge(mat.stromal2, clin.tcycif, by = c("cycif.slide", "cycif.core.id")) 

#For Min.Max normalization
mat.stromal2 <- scale.dataset(dat.stromal.clin2, interesting.channels.stromal,
                             last.antibody.channel = 9, norm.by = "cycif.slide")

mat.cancer2 <- scale.dataset(dat.cancer.clin2, interesting.channels.cancer,
                             last.antibody.channel = 10, norm.by = "cycif.slide")

mat.stromal2 <- as.data.frame(mat.stromal2)
mat.cancer2 <- as.data.frame(mat.cancer2)

mat.cancer2$Metacluster.ID <- dat.cancer.clin2$Metacluster.ID
mat.stromal2$Metacluster.ID <- dat.stromal.clin2$Metacluster.ID

#Generating heatmaps of marker expression by cell.type
ind.plots.cancer = index_plots(mat.cancer2, mat.cancer2,
                        gates.input=list(Pos=interesting.channels.cancer),
                        scaling = "NONE", log2.transform = FALSE,
                        GlobalCellType = "Metacluster.ID")

ind.plots.stromal = index_plots(mat.stromal2, mat.stromal2,
                        gates.input=list(Pos=interesting.channels.stromal),
                        scaling = "NONE", log2.transform = FALSE,
                        GlobalCellType = "Metacluster.ID")

#Saving heatmaps
pdf(file= paste0(outout.folder.name,"/Metaclusters_Cancer_Heatmap_Slide-scaled20230221.pdf"), height = 8, width = 10)
print(ind.plots.cancer[[3]])
dev.off()

#Saving heatmaps
pdf(file= paste0(outout.folder.name,"/Metaclusters_Stromal_Heatmap_Slide-scaled20230221.pdf"), height = 8, width = 10)
print(ind.plots.stromal[[3]])
dev.off()

#Only for Z-score normalization
mat.stromal3 <- scale.dataset(dat.stromal.clin2, interesting.channels.stromal,
                             last.antibody.channel = 9, norm.by = "cycif.slide")

mat.cancer3 <- scale.dataset(dat.cancer.clin2, interesting.channels.cancer,
                             last.antibody.channel = 10, norm.by = "cycif.slide")

mat.stromal3 <- as.data.frame(mat.stromal2)
mat.cancer3 <- as.data.frame(mat.cancer2)

mat.cancer3$Metacluster.ID <- dat.cancer.clin2$Metacluster.ID
mat.stromal3$Metacluster.ID <- dat.stromal.clin2$Metacluster.ID

#Generating heatmaps of marker expression by cell.type
ind.plots.cancer = index_plots(mat.cancer3, mat.cancer3,
                        gates.input=list(Pos=interesting.channels.cancer),
                        scaling = "NONE", log2.transform = FALSE,
                        GlobalCellType = "Metacluster.ID")

ind.plots.stromal = index_plots(mat.stromal3, mat.stromal3,
                        gates.input=list(Pos=interesting.channels.stromal),
                        scaling = "NONE", log2.transform = FALSE,
                        GlobalCellType = "Metacluster.ID")

#Saving heatmaps
pdf(file= paste0(outout.folder.name,"/Metaclusters_Cancer_Heatmap_Slide-scaled_Zscore.pdf"),
    height = 8, width = 10)
print(ind.plots.cancer[[3]])
dev.off()

#Saving heatmaps
pdf(file= paste0(outout.folder.name,"/Metaclusters_Stromal_Heatmap_Slide-scaled_Zscore.pdf"),
    height = 8, width = 10)
print(ind.plots.stromal[[3]])
dev.off()


#Generating UMAPs, with labels by clusters and channel intensities
mycolors.clusters <- colorRampPalette(brewer.pal(12, "Paired"))(12)
metacluster_types <- factor(mat.stromal2$Metacluster.ID,
                            levels=(unique(mat.stromal2$Metacluster.ID)))
#Metacluster
umaps.stromal <- channel.UMAPs(mat.stromal2[,interesting.channels.stromal], metacluster_types,
                               extralabel=list(dat.stromal.clin2$cycif.slide,
                                               dat.stromal.clin2$therapy_sequence,
                                               dat.stromal.clin2$Molecular_profile,
                                               dat.stromal.clin2$incyear),
                               rowselectionstatus=NULL, sub.sample = TRUE, n.sampling = 25000,
                               user.colors=mycolors.clusters, umap_neighbors =50, umap_mindist=0.2)


metacluster_types <- factor(mat.cancer2$Metacluster.ID, levels=(unique(mat.cancer2$Metacluster.ID))) 
umaps.cancer <- channel.UMAPs(mat.cancer2[,interesting.channels.cancer], metacluster_types,
                               extralabel=list(dat.cancer.clin2$cycif.slide,
                                               dat.cancer.clin2$therapy_sequence,
                                               dat.cancer.clin2$Molecular_profile,
                                               dat.cancer.clin2$incyear),
                               rowselectionstatus=NULL, sub.sample = TRUE, n.sampling = 25000,
                               user.colors=mycolors.clusters, umap_neighbors =50, umap_mindist=0.2)

umap.outputnames <- c("clusterLabel","Slide", "Therapy", "MolProfile","Year")

ggsave(file=paste0(outout.folder.name,"/Metaclusters_Stromal_UMAPs_channels_Slide-scaled2.pdf"),
       arrangeGrob(grobs = umaps.stromal[[1]], ncol = 4), height = 12, width = 10)
ggsave(file=paste0(outout.folder.name,"/Metaclusters_Stromal_UMAPs_channels_Slide-scaled2.png"),
       arrangeGrob(grobs = umaps.stromal[[1]], ncol = 4), height = 5.3, width = 6.1)
for (i in 2:length(umaps.stromal)){
  j <- i-1
  ggsave(file=paste0(outout.folder.name,"/Metaclusters_Stromal_UMAPs_",umap.outputnames[j],"_Slide-scaled2.pdf"),
       umaps.stromal[[i]], height = 6.89, width = 7.93)
}

ggsave(file=paste0(outout.folder.name,"/Metaclusters_Cancer_UMAPs_channels_Slide-scaled2.pdf"),
       arrangeGrob(grobs = umaps.cancer[[1]], ncol = 4), height = 12, width = 10)
ggsave(file=paste0(outout.folder.name,"/Metaclusters_Cancer_UMAPs_channels_Slide-scaled2.png"),
       arrangeGrob(grobs = umaps.cancer[[1]], ncol = 4), height = 7, width = 8)
for (i in 2:length(umaps.cancer)){
  j <- i-1
  ggsave(file=paste0(outout.folder.name,"/Metaclusters_Cancer_UMAPs_",umap.outputnames[j],"_Slide-scaled2.pdf"),
       umaps.cancer[[i]], height = 6.89, width = 7.93)
}

```



```{r}
#Counting the abundance of metaclusters per slide
dat.stromal.clin$Metacluster.ID <- mat.stromal2$Metacluster.ID
dat.cancer.clin$Metacluster.ID <- mat.cancer2$Metacluster.ID

cluster.counts.strom  <- dat.stromal.clin %>% 
                         group_by(Metacluster.ID, cycif.slide) %>%
                         summarise(N = n()) %>%
                         mutate(Total_in_cluster = sum(N), 
                         Ratio = round(N/Total_in_cluster, 2))

cluster.counts.can  <- dat.cancer.clin %>% 
                         group_by(Metacluster.ID, cycif.slide) %>%
                         summarise(N = n()) %>%
                         mutate(Total_in_cluster = sum(N), 
                         Ratio = round(N/Total_in_cluster, 2))
p.strom = ggplot(cluster.counts.strom, aes(x=Metacluster.ID, y=Ratio, fill=cycif.slide)) + 
      geom_bar(stat="identity", color="black", position=position_dodge()) +
      theme_minimal() + labs(title="Stromal metaclusters")


p.can= ggplot(cluster.counts.can, aes(x=Metacluster.ID, y=Ratio, fill=cycif.slide)) + 
      geom_bar(stat="identity", color="black", position=position_dodge()) +
      theme_minimal() + labs(title="Cancer metaclusters")


#Counting the abundance of metaclusters per therapy
cluster.counts.strom2  <- dat.stromal.clin %>% 
                         group_by(Metacluster.ID, therapy_sequence) %>%
                         summarise(N = n()) %>%
                         mutate(Total_in_cluster = sum(N), 
                         Ratio = round(N/Total_in_cluster, 2))

cluster.counts.can2  <- dat.cancer.clin %>% 
                         group_by(Metacluster.ID, therapy_sequence) %>%
                         summarise(N = n()) %>%
                         mutate(Total_in_cluster = sum(N), 
                         Ratio = round(N/Total_in_cluster, 2))

p2.strom = ggplot(cluster.counts.strom2, aes(x=Metacluster.ID, y=Ratio, fill=therapy_sequence)) + 
          geom_bar(stat="identity", color="black", position=position_dodge()) +
          theme_minimal() + labs(title="Stromal metaclusters")


p2.can  = ggplot(cluster.counts.can2, aes(x=Metacluster.ID, y=Ratio, fill=therapy_sequence)) + 
          geom_bar(stat="identity", color="black", position=position_dodge()) +
          theme_minimal() + labs(title="Cancer metaclusters")


#Counting the abundance of metaclusters per molecular profile
cluster.counts.strom3  <- dat.stromal.clin %>% 
                         group_by(Metacluster.ID, Molecular_profile) %>%
                         summarise(N = n()) %>%
                         mutate(Total_in_cluster = sum(N), 
                         Ratio = round(N/Total_in_cluster, 2))

cluster.counts.can3  <- dat.cancer.clin %>% 
                         group_by(Metacluster.ID, Molecular_profile) %>%
                         summarise(N = n()) %>%
                         mutate(Total_in_cluster = sum(N), 
                         Ratio = round(N/Total_in_cluster, 2))


p3.strom = ggplot(cluster.counts.strom3, aes(x=Metacluster.ID, y=Ratio, fill=Molecular_profile)) + 
          geom_bar(stat="identity", color="black", position=position_dodge()) +
          theme_minimal() + labs(title="Stromal metaclusters")


p3.can  = ggplot(cluster.counts.can3, aes(x=Metacluster.ID, y=Ratio, fill=Molecular_profile)) + 
          geom_bar(stat="identity", color="black", position=position_dodge()) +
          theme_minimal() + labs(title="Cancer metaclusters")

#Saving plots
ggsave(p.strom, filename = paste0(outout.folder.name, "Metaclusters_Stromal_slide_ratio2",".png"),
       width = 24, height = 10, units = "cm")

ggsave(p.can, filename = paste0(outout.folder.name, "Metaclusters_Cancer_slide_ratio2",".png"),
       width = 24, height = 10, units = "cm")

ggsave(p2.strom, filename = paste0(outout.folder.name, "Metaclusters_Stromal_therapy_ratio2",".png"),
       width = 24, height = 10, units = "cm")

ggsave(p2.can, filename = paste0(outout.folder.name, "Metaclusters_Cancer_therapy_ratio2",".png"),
       width = 24, height = 10, units = "cm")

ggsave(p3.strom, filename = paste0(outout.folder.name, "Metaclusters_Stromal_MolProfile_ratio2",".png"),
       width = 24, height = 10, units = "cm")

ggsave(p3.can, filename = paste0(outout.folder.name, "Metaclusters_Cancer_MolProfile_ratio2",".png"),
       width = 24, height = 10, units = "cm")
```



```{r}
#Writing results in Napary format
CoreSuffix <- "_Probabilities_cytomask2"
project.folder <- "D:/users/fperez/NKI_TMAs_AF/"
outputfolder <- "Metaclusters_Napary2023"

for (i in unique(dat.stromal$cycif.slide)){
  dir.create(paste0(project.folder, "/", i,"/", outputfolder))
  set.stromal <- dat.stromal[dat.stromal$cycif.slide == i,]
  set.stromal$Metacluster.ID <- sub("Cluster","StromalClus",set.stromal$Metacluster.ID)
  set.cancer <- dat.cancer[dat.cancer$cycif.slide == i,]
  set.cancer$Metacluster.ID <- sub("Cluster","CancerClus",set.cancer$Metacluster.ID)
  cells.slide <- rbind(set.stromal, set.cancer)
  for (core in unique(cells.slide$cycif.core.id)){
    cells.core <- cells.slide[cells.slide$cycif.core.id == core,]
    df <- data.frame(Core_Names=paste0(cells.core$cycif.core.id,CoreSuffix),
                     Cellid=cells.core$CellId,
                     lost=cells.core$lost,
                     GlobalCellType=cells.core$Metacluster.ID)
    df <- df[order(df$Cellid),]
    write.table(df, file=paste0(project.folder, i,"/", outputfolder,"/",core,"_metaclusters_Napary.csv"),
                sep=",", row.names = FALSE)
  }
}
```


```{r}
#Merging immune data with clinical data
colnames(dat.immune)[ncol(dat.immune)] <- colnames(clin.tcycif)[2]
colnames(dat.immune)[2] <- colnames(clin.tcycif)[3]
immune.dat <- merge(dat.immune, clin.tcycif, by = c("cycif.slide", "cycif.core.id")) 
```


```{r}
#Merging results and writing them in tables
stromal.dat$GlobalCellType <- stromal.dat$Metacluster.ID
stromal.dat <- stromal.dat[,-ncol(stromal.dat)]

cancer.dat$GlobalCellType <- cancer.dat$Metacluster.ID
cancer.dat <- cancer.dat[,-ncol(cancer.dat)]

dataset.clusters <- rbind(stromal.dat, immune.dat, cancer.dat)

dataset.clusters$GlobalCellType[1:1633558] <- gsub("Cluster","StromalC",dataset.clusters$GlobalCellType[1:1633558])

dataset.clusters$GlobalCellType[2954964:4568217] <- gsub("Cluster","CancerC",dataset.clusters$GlobalCellType[2954964:4568217])
```

```{r}
#Writing results
write.table(file="D:/users/fperez/NKI_TMAs_AF/Tables/All.cells_clusters.csv",dataset.clusters[,c(1:73,100,106)], sep=",", row.names=FALSE)
```



```{r}
cells_percentages <- dataset.clusters %>% group_by(patient, GlobalCellType) %>% summarise(n = n()) %>% mutate(proportion = n * 100 / sum(n))
cells_percentages <- as.data.frame(cells_percentages)
cells_percentages <- cells_percentages[,-3]

cells_percentages.m <- cells_percentages %>% pivot_wider(names_from = GlobalCellType, values_from = proportion)

cells_percentages.m <- as.data.frame(cells_percentages.m)
row.names(cells_percentages.m) <- cells_percentages.m[,1]
cells_percentages.m <- cells_percentages.m[,-1]
cells_percentages.m[is.na(cells_percentages.m)] <- 0
cells_percentages.m <- as.matrix(cells_percentages.m)
cells_percentages.scaled <- scale(cells_percentages.m)

#Getting molecular profile of patients using same order as matrix
Profiles.m <- sapply(row.names(cells_percentages.m), function(x) {
  clin.tcycif[which(clin.tcycif$patient == x)[1],"Molecular_profile"] })
Profiles.m[which(Profiles.m == "")] <- "Other"
Profiles.m[which(Profiles.m == "BRCAmut OR hypermethylation")] <- "BRCAmut"
Profiles.m[which(Profiles.m == "BRCAness & CCNE1")] <- "BRCAness&CCNE1"


#Getting therapy sequence of patients using same order as matrix
therapy <- sapply(row.names(cells_percentages.m), function(x) {
  clin.tcycif[which(clin.tcycif$patient == x)[1],"therapy_sequence"] })
therapy[which(therapy == "PDS followed by NACT")] <- "PDS"
therapy[which(therapy == "Primairy debulking")] <- "PDS"
therapy[which(therapy == "Only debulking")] <- "PDS"
therapy[which(therapy == "NACT followed by re-debulking")] <- "NACT"

colours <- list(Therapy=c("NACT"="black", "PDS"="grey90"),
                M.profile=c("BRCAmut" = "darkred", "BRCAness" = "orange", "CCNE1"="darkblue",
                            "BRCAness&CCNE1"="purple", "Other"="#50B1FC"))

ha = rowAnnotation(Therapy=therapy, M.profile=Profiles.m, col =colours)

set.seed(123)
col_c <- colorRamp2(c(-1.5, 0, 2, 4), c("#0000FF","grey95", "#F9AAAA", "#EE0000"))
hmap1 <- Heatmap(cells_percentages.scaled, name="Subtype %\nper patient (Z-score)",
                row_names_gp = gpar(fontsize = 3), column_names_gp = gpar(fontsize = 10),
                row_names_side = "left", row_dend_side = "right",
                col=col_c, row_km = 3, column_km = 4,
                right_annotation = ha, column_names_rot = 65)

draw(hmap1)
```

```{r}
cells_percentages.nac <- cells_percentages.scaled[which(therapy == "NACT"),]
cells_percentages.pds <- cells_percentages.scaled[which(therapy == "PDS"),]


colours2 <- list(M.profile=c("BRCAmut" = "darkred", "BRCAness" = "orange", "CCNE1"="darkblue",
                            "BRCAness&CCNE1"="purple", "Other"="lightblue"))

ha = rowAnnotation(M.profile=Profiles.m[which(therapy == "PDS")], col=colours2)

set.seed(321)
col_c <- colorRamp2(c(-1.5, 0, 2, 4), c("#0000FF","grey95", "#F9AAAA", "#EE0000"))
hmap1 <- Heatmap(cells_percentages.pds, name="Subtype %\nper patient (Z-score)",
                row_names_gp = gpar(fontsize = 3), column_names_gp = gpar(fontsize = 10),
                row_names_side = "left", row_dend_side = "right",
                col=col_c, row_km = 3, column_km = 3,
                right_annotation = ha)

draw(hmap1)
```

