---
title: "R Notebook"
output: html_notebook
---

```{r}
#Loading dependencies
library(ggplot2)
library(reshape)
library(gridExtra)
library(tidyverse)
library(RColorBrewer)
source("D:/users/fperez/NKI_TMAs_AF/devNKI-scripts/3_Cell-typeClassification/qc_functions.R")
source("D:/users/fperez/NKI_TMAs_AF/devNKI-scripts/3_Cell-typeClassification/cell_type_caller_functions.R")
source("D:/users/fperez/NKI_TMAs_AF/devNKI-scripts/3_Cell-typeClassification/gates_NKI.R")

outout.folder.name <- "D:/users/fperez/NKI_TMAs_AF/Manuscript_figures/"
```

```{r}
#Declaring functions

#Function to scale dataset
scale.dataset <- function(dataset){
  table.data  <- log2(dataset)
  data.filtered.trim <- z.trimming(table.data)
  table.data <- data.filtered.trim[[1]]
  scale(table.data)
}
```


```{r}
#Reading input
whole.dataset <- read.table(file="D:/users/fperez/NKI_TMAs_AF/Tables/All_slides_cellTypes.csv", sep=",", header = TRUE)
```



```{r}
#Loading clinical info
cycif2samples <- read.table(file="D:/users/fperez/NKI_TMAs_AF/devNKI-scripts/3_Cell-typeClassification/tCicyf_patients-cores_pass.csv", sep=",", header = TRUE)
clinical.info <- read.table(file="D:/users/fperez/NKI_TMAs_AF/Clinical_data/T-CycIF.csv", sep=",", header = TRUE)

clin.tcycif <- merge(cycif2samples, clinical.info, by.x="patient", by.y="TnumberAVL")

clin.tcycif$cycif.core.id <- as.numeric(gsub("core","",clin.tcycif$cycif.core.id))
```


```{r}
#Ignoring cells with low DAPI expression, possibly those are not real cells
#Splitting by cell-types
dataset <- whole.dataset[whole.dataset$GlobalCellType != "LowDapi",]

dat.immune <- dataset[dataset$GlobalCellType != "Cancer" & 
                        !grepl("Stromal", dataset$GlobalCellType),]
dat.cancer <- dataset[dataset$GlobalCellType == "Cancer",]
dat.stromal <- dataset[grepl("Stromal", dataset$GlobalCellType),]
```



```{r}
#Generating heatmaps of marker expression by cell.type
ind.plots.global = index_plots(dataset, dataset,
                        gates.input=c(global.gates, immune.gates, Lymphoid.gate, Myeloid.gate),
                        scaling = "z.score", log2.transform = TRUE)

ind.plots.immune = index_plots(dat.immune, dat.immune,
                        gates.input=c(global.gates, immune.gates, Lymphoid.gate, Myeloid.gate),
                        scaling = "z.score", log2.transform = TRUE)


pdf(file= paste0(outout.folder.name,"Fig1b_celltypes_markerExpression.pdf"),
    height = 6, width = 8)
print(ind.plots.global[[3]])
dev.off()

pdf(file= paste0(outout.folder.name,"SupFig1b_Immunecelltypes_markerExpression.pdf"),
    height = 6, width = 8)
print(ind.plots.immune[[3]])
dev.off()
```



```{r}
##########Generating UMAPs for immune cells, global data, cancer cells and stromal
#Downsampling the data, to select only 25k cells

immune.interesting.channels <- unique(unlist(c(Myeloid.gate, immune.gates, Lymphoid.gate)))
global.interesting.channels <- unique(unlist(global.gates))

global.data <- dataset[ ,global.interesting.channels]
global.data <- as.data.frame(scale.dataset(global.data))
global.types <- dataset[ ,"GlobalCellType"]
global.types[grep("Stromal",global.types)] <- "Stromal" #Merging stromal types
global.types[which(global.types != "Cancer" &  global.types != "Stromal")] <- "Immune" #Merging Immune types
global.cell_types <- factor(global.types, levels=(unique(global.types))) #Cell type for each row

immune.data <- dat.immune[ ,immune.interesting.channels]
immune.data <- as.data.frame(scale.dataset(immune.data))
immune.types <- dat.immune[ ,"GlobalCellType"]
immune.cell_types <- factor(immune.types, levels=(unique(immune.types))) #Cell type for each row

mycolors.global <- c("#17781f", "#2d6da8", "#a743cc")
mycolors.immune <- colorRampPalette(brewer.pal(10, "Paired"))(10)

umaps.immune <- channel.UMAPs(immune.data, immune.cell_types, sub.sample = TRUE,
                              n.sampling = 25000, user.colors=mycolors.immune,
                              umap_neighbors =50, umap_mindist=0.2)
umaps.global <- channel.UMAPs(global.data, global.cell_types, sub.sample = TRUE,
                              n.sampling = 25000, user.colors=mycolors.global,
                              umap_neighbors =80, umap_mindist=0.5)


ggsave(file=paste0(outout.folder.name,"SupFig1_Global_UMAPs_channels.pdf"),
       arrangeGrob(grobs = umaps.global[[1]], ncol = 4), height = 12, width = 10)
ggsave(file=paste0(outout.folder.name,"SupFig1_Global_UMAPs_channels.png"),
       arrangeGrob(grobs = umaps.global[[1]], ncol = 4), height = 5.3, width = 6.1)
ggsave(file=paste0(outout.folder.name,"Fig1c_Global_UMAPs_celltypes.pdf"),
       umaps.global[[2]], height = 6.89, width = 7.93)
ggsave(file=paste0(outout.folder.name,"Fig1c_Global_UMAPs_celltypes.png"),
       umaps.global[[2]], height = 7.89, width = 8.93, units="cm")


ggsave(file=paste0(outout.folder.name,"SupFig1_Immune_UMAPs_channels.pdf"),
       arrangeGrob(grobs = umaps.immune[[1]], ncol = 4), height = 12, width = 10)
ggsave(file=paste0(outout.folder.name,"SupFig1_Immune_UMAPs_channels.png"),
       arrangeGrob(grobs = umaps.immune[[1]], ncol = 4), height = 5.3, width = 6.1)
ggsave(file=paste0(outout.folder.name,"Fig1d_Immune_UMAPs_celltypes.pdf"),
       umaps.immune[[2]], height = 6.89, width = 7.93)
ggsave(file=paste0(outout.folder.name,"Fig1d_Immune_UMAPs_celltypes.png"),
       umaps.immune[[2]], height = 7.89, width = 8.93, units="cm")

```





```{r}
#Generating table of number of cells, by core and slide

#Adding slide names in last column
slidenames <- sapply(dataset$Row_number, function(x){
  splitted <- strsplit(x, "_")[[1]]
  paste(splitted[1],splitted[2],splitted[3], sep="_")
  })

dataset$Slide <- slidenames

#Creating temporal dataframe
dataset2 <- dataset 
#Merging stromal
dataset2[grep("Stromal",dataset2$GlobalCellType),"GlobalCellType"] <- "Stromal"

cell.counts.core <- dataset2 %>% 
          group_by(Slide, CoreId) %>%
          summarise(celltype_count = table(GlobalCellType),
                    celltype = names(table(GlobalCellType)))

cell.counts.core <- as.data.frame(cell.counts.core)
cells.by.core <- spread(cell.counts.core, key=celltype, value=celltype_count, fill = 0)
```

#Cell type abundance intrapatient
```{r}
#Merging table of cell abundance with patient data
counts <- cells.by.core[,3:ncol(cells.by.core)]
counts.norm <- t(apply(counts, 1, function(x){ round(x /sum(x), 3)}))
cells.by.core[,3:ncol(cells.by.core)] <- counts.norm

colnames(cells.by.core)[1:2] <- c("cycif.slide","cycif.core.id")
merged.cells.by.core <- merge(cells.by.core, clin.tcycif, by=c("cycif.slide","cycif.core.id"))
merged.cells.by.core



 df.cancer <- NULL
 df.stromal <- NULL
 for (p in unique(unique(merged.cells.by.core$patient))){
   patient.cores <- merged.cells.by.core[merged.cells.by.core$patient %in% p,]
   ordered.percentages.cancer <- order(patient.cores$Cancer)
   ordered.percentages.stromal <- order(patient.cores$Stromal)
   if (length(ordered.percentages.cancer) == 4){
     median.min <- median(patient.cores$Cancer[ordered.percentages.cancer[c(1,2)]])
     median.max <- median(patient.cores$Cancer[ordered.percentages.cancer[c(3,4)]])
     diff <-  median.max - median.min
     names(diff) <- p 
     df.cancer <- c(df.cancer,diff)
     median.min <- median(patient.cores$Stromal[ordered.percentages.stromal[c(1,2)]])
     median.max <- median(patient.cores$Stromal[ordered.percentages.stromal[c(3,4)]])
     diff <-  median.max - median.min
     names(diff) <- p 
     df.stromal <- c(df.stromal,diff)
   }
 }
 
 barplot(sort(df.cancer), ylab="Median difference", main="Cancer cell abundance difference intra patients",xaxt = "n")
 
  barplot(sort(df.stromal), ylab="Median difference", main="Stromal cell abundance difference intra patients",xaxt = "n")

```

