---
title: "R Notebook"
output: html_notebook
---

```{r}
library(corrplot)
library(RColorBrewer)
library(reshape2)
library(ggplot2)
library(gridExtra)
library(ggpubr)
#library(CytoTree)
library(flowCore)
library(stringr)
library("dplyr")
theme_set(theme_pubr())
library(FlowSOM)
library(circlize)
library(ComplexHeatmap)


source("D:/users/fperez/NKI_TMAs_AF/devNKI-scripts/3_Cell-typeClassification/qc_functions.R")
source("D:/users/fperez/NKI_TMAs_AF/devNKI-scripts/3_Cell-typeClassification/cell_type_caller_functions.R")

project.path <- "D:/users/fperez/NKI_TMAs_AF/"
outout.folder.name <- "D:/users/fperez/NKI_TMAs_AF/Analysis_results/02_MetaClusters_November"
tribus.subfolder <- "Tribus_Cell-segment_202311"
celltypes.file.suffix = "_cellTypes.csv"

set.seed(76418)
```

#Reading clinical info

```{r}
cycif2samples <- read.table(file="D:/users/fperez/NKI_TMAs_AF/devNKI-scripts/3_Cell-typeClassification/tCicyf_patients-cores_pass.csv", sep=",", header = TRUE)
clinical.info <- read.table(file="D:/users/fperez/NKI_TMAs_AF/Clinical_data/T-CycIF.csv", sep=",", header = TRUE)

clin.columns.interest <- c("TnumberAVL","CFsample","centre","incyear","figo_stage",
                           "Molecular_profile","therapy_sequence")

clinical.info <- clinical.info[,clin.columns.interest]

clin.tcycif <- merge(cycif2samples, clinical.info, by.x="patient", by.y="TnumberAVL")
```

#Reading input tCycif data and cell.type data

```{r}
#List all the tables with celltype labels
big.data.set <- NULL
files <- list.files(path=project.path, pattern = "TMA_", full.names = T)
#Read all cell.type and signal intensity data
for (f in files){
  cycif.slide <- basename(f)
  slide.data <- read.table(file=paste0(f, "/", tribus.subfolder, "/", cycif.slide, celltypes.file.suffix), sep=",", header=TRUE)
  slide.data <- cbind(cycif.slide, slide.data)
  slide.data$Row_number <- paste0(cycif.slide,":",slide.data$Row_number)
  colnames(slide.data)[colnames(slide.data) == "CoreId"] <- "cycif.core.id"
  slide.data$cycif.core.id <- paste0("core",slide.data$cycif.core.id)
  big.data.set <- rbind(big.data.set,slide.data)
}
```

#QC and filtering of the cell.type dataset

```{r}
#Performing QC according to cell.types
#Ignoring cell with low DAPI intensity and out of the core
big.data.set <- big.data.set %>% dplyr::filter(GlobalCellType != "LowDapi")

dat.cancer <- big.data.set %>% dplyr::filter(GlobalCellType == "Cancer")
```


```{r}
#Functions to be used for the metaclustering of cancer and stromal cells

#Function to scale the dataset
scale.dataset <- function(dataset, channels, last.antibody.channel=11, norm.by=NA, min.max=TRUE){
  if (!is.na(norm.by)){
    table.scaled <- NULL
    for (i in unique(dataset[,norm.by])){
      data.subset <- dataset[dataset[,norm.by] %in% i,channels]
      #Log2 for antibody intensity channels
      table.dat  <- log2(data.subset[,1:last.antibody.channel]) 
      #Truncating intensity data to 0.99 percentile only the channels
      trimmed.list <- z.trimming(table.dat, max.quantile=0.99, min.quantile=0.001) 
      table.dat.trim <- trimmed.list[[1]]
      #Truncating morphology data to 0.999
      morphology.dat <- data.subset[,(last.antibody.channel+1):length(channels)]
      trimmed.list <- z.trimming(morphology.dat, max.quantile=0.999) 
      morphology.dat.trim <- trimmed.list[[1]]
      #Rest of the columns correspond to morphology features, not log2 for them
      mat.dat = cbind(table.dat.trim, morphology.dat.trim) 
      table.scaled.set <- scale(mat.dat) #Z-score normalization
      if(min.max){
        table.scaled.set <- apply(table.scaled.set,2,min_max_norm) #Min.Max normalization
      }
      table.scaled <- rbind(table.scaled, table.scaled.set)
    }
  }else{
    table <- dataset[,channels]
    table.dat  <- log2(table[,1:last.antibody.channel])
    table = cbind(table.dat, table[,(last.antibody.channel+1):length(channels)])
    data.filtered.trim <- z.trimming(table)
    mat.dat <- data.filtered.trim[[1]]
    table.scaled <- scale(mat.dat)
    if(min.max){
      table.scaled <- apply(table.scaled,2,min_max_norm) #Min.Max normalization
    }
  }
  return(table.scaled)
}

#Running FloWSOM and 
som.metaclustering.consensus <- function(dataset, max.kval =12, tempdir){
dir.create(tempdir)
print("Starting FLOWSOM")
out.som <- FlowSOM::ReadInput(dataset, transform = FALSE, scale = FALSE)
out.som <- FlowSOM::BuildSOM(out.som, colsToUse = colnames(dataset), silent=T, xdim=50, ydim=50)
out.som <- FlowSOM::BuildMST(out.som, silent=T)
print("Starting consensus clustering")
out.results <- suppressMessages(ConsensusClusterPlus::ConsensusClusterPlus(t(out.som$map$codes),
        maxK = max.kval, reps = 500, pItem = 0.8, pFeature = 0.9, title = tempdir, 
        plot = "png", verbose = FALSE, clusterAlg = "pam", 
        distance = "euclidean", seed = 81))
#metaclusters <- out.results[[kval]]$consensusClass
#return(metaclusters[out.som$map$mapping[,1]])
return(list(out.results,out.som))
}
```

#Running SOM and consensus clustering for the stromal and cancer cells

```{r}
###############Metaclustering of the cells###########
interesting.channels.cancer <- c("Ki67","Vimentin","pSTAT1", "MHCI", "ECadherin","yH2AX",
                                 "pTBK1", "cPARP1", "CK7","PDL1_488","Area",
                                 "Eccentricity", "Roundness")


#Scaling datasets
mat.cancer <- scale.dataset(dat.cancer, interesting.channels.cancer,
                             last.antibody.channel = 10, norm.by = "cycif.slide")

#Directories where to store the consensus clustering plots of the SOM nodes
tmpdir.cancer <- "D:/users/fperez/NKI_TMAs_AF/Analysis_results/02_MetaClusters_November/SOM_consensusClusters_cancer2/"

som.consensus.cancer <- som.metaclustering.consensus(mat.cancer, tempdir=tmpdir.cancer)
```

#Selecting the number of metaclusters according to the results of consensus clustering
```{r}
k.cancer <- 4

consensus.cancer <- som.consensus.cancer[[1]]
som.cancer <- som.consensus.cancer[[2]]
consensus.cancer.k <- consensus.cancer[[k.cancer]]$consensusClass

#Extraction of metaclusters ids per cell
metalabels.cancer <- consensus.cancer.k[som.cancer$map$mapping[,1]]
```


```{r}
#A big function to plot UMAPs, downscaling dataset
#Extralabels should be a list of vectors
channel.UMAPs <- function(df, cell.labels, extralabels=NULL, rowselectionstatus=NULL,
                          sub.sample=FALSE,
                          n.sampling=10000, user.colors=mycolors, umap_neighbors=30, umap_mindist=0.30){
  if (!is.null(rowselectionstatus)){
    df <- df[rowselectionstatus,]
  }
  
  if (sub.sample){
    sampling.rows <- sample(1:nrow(df), n.sampling)
    df <- df[sampling.rows,]
    cell.labels <- cell.labels[sampling.rows]
    if (!is.null(extralabels)){
      for (i in 1:length(extralabels)){
        extralabels[[i]] <- extralabels[[i]][sampling.rows]
      }
    }
  }
  
  umap_s = uwot::umap(df, n_neighbors = umap_neighbors, scale=FALSE, spread=1.5,
                      min_dist = umap_mindist, n_epochs = 60)
  
  uplot = data.frame(x = umap_s[,1], y= umap_s[,2])
  pltChannels <- list()
  pltChannels <- lapply(1:ncol(df), function(x){
    markers <- df[, x]
    p = ggplot(data=uplot,aes(x,y, color=markers)) + geom_point(size=0.3, stroke=0, alpha=0.7)+ 
      #guides(color = guide_legend(override.aes = list(size=5))) + 
      theme_bw() + coord_fixed(ratio=1)+ 
      xlab("umap1") + ylab("umap2") + theme(aspect.ratio=1) + theme(legend.position="none") +
      scale_colour_gradient(low = "#103254", high="green")
    p <- p + ggtitle(colnames(df)[x])
    return(p)
  })
  
  Subtype <- factor(cell.labels, levels=unique(cell.labels))
  #df <- cbind(df$Subtype)
  
  pl = ggplot(uplot,aes(x,y, color=Subtype))+ geom_point(size=0.4, stroke=0, alpha=0.7)+ 
    scale_fill_viridis(discrete = TRUE) + 
    guides(color = guide_legend(override.aes = list(size=10))) + 
    scale_color_manual(values=user.colors) + theme_bw() + coord_fixed(ratio=1)+
    guides(colour = guide_legend(override.aes = list(size=20, shape=15, alpha=1),
                                 direction="horizontal", ncol=1, label.position="bottom", byrow=F)) + 
    xlab("umap1") + ylab("umap2") + 
    theme(legend.title = element_blank(), aspect.ratio=1.1,
      legend.text=element_text(size=rel(2.5)),
      axis.text.x=element_text(size=rel(3)),
      axis.text.y=element_text(size=rel(3)),
      axis.title.y =element_text(size=rel(3)),
      axis.title.x =element_text(size=rel(3)))
  
  plots = list(pltChannels,pl)
  
  colors2 <- colorRampPalette(brewer.pal(12, "Paired"))(10)
  
  if(!is.null(extralabels)){
    pltExtras <- lapply(1:length(extralabels), function(x){
      extralabel <- factor(extralabels[[x]], levels=unique(extralabels[[x]]))
      px = ggplot(uplot,aes(x,y, color=extralabel))+ geom_point(size=0.4, stroke=0, alpha=0.7)+ 
          geom_density_2d(color="grey60", alpha=0.6) +
          scale_fill_viridis(discrete = TRUE) + 
          guides(color = guide_legend(override.aes = list(size=10))) + 
          scale_color_manual(values=colors2) + theme_bw() + coord_fixed(ratio=1)+
          guides(colour = guide_legend(override.aes = list(size=10, shape=15, alpha=1),
          direction="horizontal", ncol=2, label.position="bottom", byrow=F)) + 
          xlab("umap1") + ylab("umap2") + #ylim(-10, 10) + 
          theme(legend.title = element_blank(), aspect.ratio=1.1,
                legend.text=element_text(size=rel(1.2)),
                axis.text.x=element_text(size=rel(1.2)),
                axis.text.y=element_text(size=rel(1.2)),
                axis.title.y =element_text(size=rel(1.2)),
                axis.title.x =element_text(size=rel(1.2)))
      return(px)
  })
  }
  plots = append(plots,pltExtras)
  return(plots)
}

```


```{r}
aux.cancer <- cells.labels %>% filter(grepl("Cancer", SubCelltype))
colnames(aux.cancer)[colnames(aux.cancer) == "SubCelltype"] <- "Metacluster.ID"
cluster.names <- c("Basal","Proliferative","EMT","Immunogenic")
names(cluster.names) <- c("CancerClus1","CancerClus2","CancerClus3","CancerClus4")
aux.cancer$Metacluster.ID <- cluster.names[aux.cancer$Metacluster.ID]
```


#Exploring metaclusters

```{r}
mat.cancer2 = aux.cancer

outout.folder.name <- "D:/users/fperez/NKI_TMAs_AF/Analysis_results/02_MetaClusters_Feb24/"
#dir.create(outout.folder.name)
# 
# #Scaling datasets
# Metacluster.ID <- paste0("Cluster",metalabels.cancer)
# mat.cancer2 <- cbind(dat.cancer, Metacluster.ID)

dat.cancer.clin2 <- merge(mat.cancer2, clin.tcycif, by = c("cycif.slide", "cycif.core.id")) 

#For Min.Max normalization after Z-score
mat.cancer2 <- scale.dataset(dat.cancer.clin2, interesting.channels.cancer,
                             last.antibody.channel = 10, norm.by = "cycif.slide")

mat.cancer2 <- as.data.frame(mat.cancer2)

mat.cancer2$Metacluster.ID <- dat.cancer.clin2$Metacluster.ID


#Generating heatmaps of marker expression by cell.type
ind.plots.cancer = index_plots(mat.cancer2, mat.cancer2,
                        gates.input=list(Pos=interesting.channels.cancer),
                        scaling = "NONE", log2.transform = FALSE,
                        GlobalCellType = "Metacluster.ID")

#Saving heatmaps with Z-score plus min-max normalization
pdf(file= paste0(outout.folder.name,"/Metaclusters_Cancer_Heatmap_MinMax.pdf"), height = 8, width = 10)
print(ind.plots.cancer[[3]])
dev.off()

#Performing Z-score normalization and no min.max
mat.cancer3 <- scale.dataset(dat.cancer.clin2, interesting.channels.cancer,
                             last.antibody.channel = 10, norm.by = "cycif.slide", min.max = FALSE)

mat.cancer3 <- as.data.frame(mat.cancer3)
mat.cancer3$Metacluster.ID <- dat.cancer.clin2$Metacluster.ID

#Generating heatmaps of marker expression by cell.type
ind.plots.cancer = index_plots(mat.cancer3, mat.cancer3,
                        gates.input=list(Pos=interesting.channels.cancer),
                        scaling = "NONE", log2.transform = FALSE,
                        GlobalCellType = "Metacluster.ID")

#Saving heatmaps for Z-score scaling only
#For Figure 1l
pdf(file= paste0(outout.folder.name,"/Metaclusters_Cancer_Heatmap_Zscore.pdf"),
    height = 8, width = 10)
print(ind.plots.cancer[[3]])
dev.off()

#Generating UMAPs, with labels by clusters and channel intensities
#mycolors.clusters <- colorRampPalette(brewer.pal(12, "Paired"))(10)
mycolors.clusters <- c("darkorange","yellow2","green2","cyan3")

#Metacluster
metacluster_types <- factor(mat.cancer2$Metacluster.ID, levels=(unique(mat.cancer2$Metacluster.ID))) 
umaps.cancer <- channel.UMAPs(mat.cancer2[,interesting.channels.cancer], metacluster_types,
                               extralabels=list(dat.cancer.clin2$cycif.slide,
                                               dat.cancer.clin2$therapy_sequence,
                                               dat.cancer.clin2$Molecular_profile,
                                               dat.cancer.clin2$incyear),
                               rowselectionstatus=NULL, sub.sample = TRUE, n.sampling = 25000,
                               user.colors=mycolors.clusters, umap_neighbors =50, umap_mindist=0.2)

umap.outputnames <- c("clusterLabel","Slide", "Therapy", "MolProfile","Year")

# ggsave(file=paste0(outout.folder.name,"/Metaclusters_Cancer_UMAPs_channel-example.pdf"), umaps.cancer[[1]][[1]],
#        height = 6.89, width = 7.93)

#For UMAPs in Extended Materials
ggsave(file=paste0(outout.folder.name,"/Metaclusters_Cancer_UMAPs_channels.pdf"),
       arrangeGrob(grobs = umaps.cancer[[1]], ncol = 4), height = 12, width = 10)
ggsave(file=paste0(outout.folder.name,"/Metaclusters_Cancer_UMAPs_channels.png"),
       arrangeGrob(grobs = umaps.cancer[[1]], ncol = 4), height = 7, width = 8)

#Saving UMAPs for Figure 1k
for (i in 2:length(umaps.cancer)){
  j <- i-1
  ggsave(file=paste0(outout.folder.name,"/Metaclusters_Cancer_UMAPs_",umap.outputnames[j],".pdf"),
       umaps.cancer[[i]], height = 6.89, width = 7.93)
}

```

```{r}
#Counting the abundance of metaclusters per slide
cluster.counts.strom  <- dat.stromal.clin2 %>% 
                         group_by(Metacluster.ID, cycif.slide) %>%
                         summarise(N = n()) %>%
                         mutate(Total_in_cluster = sum(N), 
                         Ratio = round(N/Total_in_cluster, 2))

cluster.counts.can  <- dat.cancer.clin2 %>% 
                         group_by(Metacluster.ID, cycif.slide) %>%
                         summarise(N = n()) %>%
                         mutate(Total_in_cluster = sum(N), 
                         Ratio = round(N/Total_in_cluster, 2))
p.strom = ggplot(cluster.counts.strom, aes(x=Metacluster.ID, y=Ratio, fill=cycif.slide)) + 
      geom_bar(stat="identity", color="black", position=position_dodge()) +
      theme_minimal() + labs(title="Stromal metaclusters")


p.can= ggplot(cluster.counts.can, aes(x=Metacluster.ID, y=Ratio, fill=cycif.slide)) + 
      geom_bar(stat="identity", color="black", position=position_dodge()) +
      theme_minimal() + labs(title="Cancer metaclusters")


#Counting the abundance of metaclusters per therapy
cluster.counts.strom2  <- dat.stromal.clin2 %>% 
                         group_by(Metacluster.ID, therapy_sequence) %>%
                         summarise(N = n()) %>%
                         mutate(Total_in_cluster = sum(N), 
                         Ratio = round(N/Total_in_cluster, 2))

cluster.counts.can2  <- dat.cancer.clin2 %>% 
                         group_by(Metacluster.ID, therapy_sequence) %>%
                         summarise(N = n()) %>%
                         mutate(Total_in_cluster = sum(N), 
                         Ratio = round(N/Total_in_cluster, 2))

p2.strom = ggplot(cluster.counts.strom2, aes(x=Metacluster.ID, y=Ratio, fill=therapy_sequence)) + 
          geom_bar(stat="identity", color="black", position=position_dodge()) +
          theme_minimal() + labs(title="Stromal metaclusters")


p2.can  = ggplot(cluster.counts.can2, aes(x=Metacluster.ID, y=Ratio, fill=therapy_sequence)) + 
          geom_bar(stat="identity", color="black", position=position_dodge()) +
          theme_minimal() + labs(title="Cancer metaclusters")


#Counting the abundance of metaclusters per molecular profile
cluster.counts.strom3  <- dat.stromal.clin2 %>% 
                         group_by(Metacluster.ID, Molecular_profile) %>%
                         summarise(N = n()) %>%
                         mutate(Total_in_cluster = sum(N), 
                         Ratio = round(N/Total_in_cluster, 2))

cluster.counts.can3  <- dat.cancer.clin2 %>% 
                         group_by(Metacluster.ID, Molecular_profile) %>%
                         summarise(N = n()) %>%
                         mutate(Total_in_cluster = sum(N), 
                         Ratio = round(N/Total_in_cluster, 2))


p3.strom = ggplot(cluster.counts.strom3, aes(x=Metacluster.ID, y=Ratio, fill=Molecular_profile)) + 
          geom_bar(stat="identity", color="black", position=position_dodge()) +
          theme_minimal() + labs(title="Stromal metaclusters")


p3.can  = ggplot(cluster.counts.can3, aes(x=Metacluster.ID, y=Ratio, fill=Molecular_profile)) + 
          geom_bar(stat="identity", color="black", position=position_dodge()) +
          theme_minimal() + labs(title="Cancer metaclusters")

#Saving barplots plots for Figure 1k
#Saving UMAP by 
ggsave(p.strom, filename = paste0(outout.folder.name, "Metaclusters_Stromal_slide_ratio2",".png"),
       width = 24, height = 10, units = "cm")

ggsave(p.can, filename = paste0(outout.folder.name, "Metaclusters_Cancer_slide_ratio2",".png"),
       width = 24, height = 10, units = "cm")

ggsave(p2.strom, filename = paste0(outout.folder.name, "Metaclusters_Stromal_therapy_ratio2",".png"),
       width = 24, height = 10, units = "cm")

ggsave(p2.can, filename = paste0(outout.folder.name, "Metaclusters_Cancer_therapy_ratio2",".png"),
       width = 24, height = 10, units = "cm")

ggsave(p3.strom, filename = paste0(outout.folder.name, "Metaclusters_Stromal_MolProfile_ratio2",".png"),
       width = 24, height = 10, units = "cm")

ggsave(p3.can, filename = paste0(outout.folder.name, "Metaclusters_Cancer_MolProfile_ratio2",".png"),
       width = 24, height = 10, units = "cm")
```

```{r}
#Merging meta.cluster IDs again to export to Napari format
Metacluster.ID <- paste0("Cluster",metalabels.cancer)
mat.cancer2 <- cbind(dat.cancer, Metacluster.ID)

Metacluster.ID <- paste0("Cluster",metalabels.stromal)
mat.stromal2 <- cbind(dat.stromal, Metacluster.ID)
```

```{r}
#Writing results in Napary format
CoreSuffix <- "_Probabilities_cytomask2"
project.folder <- "D:/users/fperez/NKI_TMAs_AF/"
outputfolder <- "Metaclusters_Napary2023_November"

#Exporing annotations
for (i in unique(mat.stromal2$cycif.slide)){
  dir.create(paste0(project.folder, "/", i,"/", outputfolder))
  set.stromal <- mat.stromal2[mat.stromal2$cycif.slide == i,]
  set.stromal$Metacluster.ID <- sub("Cluster","StromalClus",set.stromal$Metacluster.ID)
  set.cancer <- mat.cancer2[mat.cancer2$cycif.slide == i,]
  set.cancer$Metacluster.ID <- sub("Cluster","CancerClus",set.cancer$Metacluster.ID)
  cells.slide <- rbind(set.stromal, set.cancer)
  for (core in unique(cells.slide$cycif.core.id)){
    cells.core <- cells.slide[cells.slide$cycif.core.id == core,]
    df <- data.frame(Core_Names=paste0(cells.core$cycif.core.id,CoreSuffix),
                     Cellid=cells.core$CellId,
                     lost=cells.core$lost,
                     GlobalCellType=cells.core$Metacluster.ID)
    df <- df[order(df$Cellid),]
    write.table(df, file=paste0(project.folder, i,"/", outputfolder,"/",core,"_metaclusters_Napary.csv"),
                sep=",", row.names = FALSE)
  }
}
```

```{r}
#Merging results and writing them in tables
dat.immune.others <- big.data.set %>% dplyr::filter(GlobalCellType != "Cancer",
                                                    !grepl("Stromal", GlobalCellType))

#Creating column SubCelltype, CD4 and CD8 cell types will go to SubCelltype column
#CD4 and CD8 subtypes will be individually merged for GlobalCellType
#Metaclusters will go to the SubCelltype column

dat.immune.others$SubCelltype <- NA

dat.immune.others$SubCelltype[grep("CD4\\.",dat.immune.others$GlobalCellType)] <-                                 
                                      dat.immune.others$GlobalCellType[grep("CD4\\.",dat.immune.others$GlobalCellType)]

dat.immune.others$GlobalCellType[grep("CD4\\.",dat.immune.others$GlobalCellType)] <- "CD4.T.cells"

dat.immune.others$SubCelltype[grep("CD8",dat.immune.others$GlobalCellType)] <-
                                          dat.immune.others$GlobalCellType[grep("CD8",dat.immune.others$GlobalCellType)]

dat.immune.others$GlobalCellType[grep("CD8",dat.immune.others$GlobalCellType)] <- "CD8.T.cells"

colnames(mat.cancer2)[which(colnames(mat.cancer2) == "Metacluster.ID")] <- "SubCelltype"
colnames(mat.stromal2)[which(colnames(mat.stromal2) == "Metacluster.ID")] <- "SubCelltype"

mat.cancer2$SubCelltype <- sub("Cluster","CancerClus",mat.cancer2$SubCelltype)
mat.stromal2$SubCelltype <- sub("Cluster","StromalClus",mat.stromal2$SubCelltype)
mat.stromal2$GlobalCellType <-"Stromal"

big.data.set.subtypes <- rbind(dat.immune.others, mat.cancer2, mat.stromal2) %>%
                                          arrange(cycif.slide, cycif.core.id, CellId) %>%
                                          select(-lost, -Inside_ROI, -out_of_core, -Row_number)
head(big.data.set.subtypes)
```


#Writing results in table format
```{r}
write.table(file="D:/users/fperez/NKI_TMAs_AF/Tables/All_cells_subtype-info_20231129.csv", big.data.set.subtypes, sep=",",
            row.names=FALSE)
```

```{r}
cells.labels <- read.table(file="D:/users/fperez/NKI_TMAs_AF/Tables/All_cells_subtype-info_20231129.csv",
                           sep=",", header = TRUE)

```


```{r}
#Writing results in scimap-format
#Creating variable imageid
big.data.set.subtypes$imageid <- paste(big.data.set.subtypes$cycif.slide,
                                       big.data.set.subtypes$cycif.core.id, sep="_")

big.data.set.subtypes$GlobalCellType[grep("Others", big.data.set.subtypes$GlobalCellType)] <- "Other"

#Writing as GlobalCelltype the cancer and stromal metaclusters ids, but merged CD4's and CD8's
aux <- big.data.set.subtypes
aux$CellId <- paste0(big.data.set.subtypes$imageid, "_c", big.data.set.subtypes$CellId)

aux1 <- aux %>% select(imageid, CellId, DNA1, Area, Eccentricity, Perimeter, Roundness, X_position,
                      Y_position, GlobalCellType)

write.table(file="D:/users/fperez/NKI_TMAs_AF/Tables/All_cells_scimap-format_columns-reduced_20231129.csv",
            aux1, sep=",",
            row.names=FALSE)

aux1$GlobalCellType[grep("Stromal", aux$GlobalCellType)] <- aux$SubCelltype[grep("Stromal", aux$GlobalCellType)]
aux1$GlobalCellType[grep("Cancer", aux$GlobalCellType)] <- aux$SubCelltype[grep("Cancer", aux$GlobalCellType)]
write.table(file="D:/users/fperez/NKI_TMAs_AF/Tables/All_cells_subtype_scimap-format1_20231129.csv", aux1, sep=",",
            row.names=FALSE)


#Writing as GlobalCelltype the cancer and stromal metaclusters ids, and subtypes of CD4's and CD8's
aux$GlobalCellType[grep("CD4.T.cells", aux$GlobalCellType)] <- aux$SubCelltype[grep("CD4.T.cells", aux$GlobalCellType)]
aux$GlobalCellType[grep("CD8.T.cells", aux$GlobalCellType)] <- aux$SubCelltype[grep("CD8.T.cells", aux$GlobalCellType)]
aux2 <- aux %>% select(imageid, CellId, DNA1, Area, Eccentricity, Perimeter, Roundness, X_position,
                      Y_position, GlobalCellType)

write.table(file="D:/users/fperez/NKI_TMAs_AF/Tables/All_cells_subtype_scimap-format2_20231129.csv", aux2, sep=",",
            row.names=FALSE)

rm(aux1)
rm(aux2)
```

```{r}
#Counting how many subtype cells are per core and saving results in table
big.data.set.subtypes.numbers  <- big.data.set.subtypes %>% group_by(imageid, SubCelltype) %>% summarise(N = n())

write.table(file=paste0(outout.folder.name, "Metaclusters_abundance_per_core_20231129.csv"),
            big.data.set.subtypes.numbers,
            sep=",", row.names=FALSE)
```
