---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
library(gridExtra)
library("dplyr")
library(ComplexHeatmap)
library(tidyr)
library(paletteer)
library(vegan)
library(circlize)



out.folder.name <- "D:/users/fperez/NKI_TMAs_AF/Analysis_results/Spatial_analysis/"
```


#Reading input cell dataset
```{r}
cells <- read.table(file="D:/users/fperez/NKI_TMAs_AF/Tables/All-cells_clusters.csv", header = TRUE, sep=",")
```


```{r}
rcn.folder <- "Analysis_results/Spatial_analysis/"
input.prefix <- "Cluster_ids_"
project.folder <- "D:/users/fperez/NKI_TMAs_AF/"
output.napari <- "RCN_Napary"

cores.interest <- c(109,110,112,114,116,118,120,122,10,11,111,113,115,117,119,121,141)
cores.interest <- sort(cores.interest)

# List all the data
files <- list.files(paste0(project.folder, rcn.folder), full.names = T)
files <- files[grepl(pattern = input.prefix, x=files)]
for (f in files){
  method.rcn <- strsplit(gsub(".csv","",basename(f)),"_")[[1]][3]
  print(method.rcn)
  RCN_clusters <- read.table(file=f, header = TRUE, sep=",")
  cells$rcn_id <- paste0("RCN",RCN_clusters$spatial_kmeans)
  n.clust <- length(unique(cells$rcn_id))
  n.clust <- n.clust-1
  cells$rcn_id <- factor(cells$rcn_id,
                         levels=paste0("RCN",0:n.clust))
  ###########################################
  #Exporting data for visualization in Napari
  for (slide in unique(cells$cycif.slide)){
    sel.cell <- cells %>%
                filter(cycif.slide == slide, cycif.core.id %in% cores.interest) %>%
                arrange(cycif.core.id, CellId)

    outout.folder.name <- paste0(project.folder, "/", slide, "/", output.napari, "_",method.rcn)
    dir.create(outout.folder.name)

    for (core in unique(sel.cell$cycif.core.id)){
      sel.cell.core <- sel.cell[which(sel.cell$cycif.core.id == core),]
      df <- data.frame(Core_Names=paste0("core",core,"_Probabilities_cytomask2"),
                     Cellid=sel.cell.core$CellId,
                     GlobalCellType=paste0("RCN",sel.cell.core$rcn_id))
      write.table(df, file=paste0(outout.folder.name,"/core",core,"_RCN_Napari.csv"),
                  sep=",", row.names = FALSE)
    }
  }

  ###########################################
  #Plotting barplot for abundance of clusters
  barplot.rcn(cells, method=method.rcn)
  
  ###########################################
  #Plotting heatmap annotations with diversity and abundance of clusters
  heatmap.diversity(cells, method=method.rcn)
}
```

#Functions to be used
```{r}
#Barplot for the RCN composition
barplot.rcn <- function(input.cells, method="NA"){
  input.cells <- cells
  cells_percentages <- input.cells %>%
                        group_by(rcn_id, GlobalCellType) %>%
                        summarise(n = n()) %>% mutate(proportion = n * 100 / sum(n))
  cells_percentages <- as.data.frame(cells_percentages)
  cells_percentages <- cells_percentages[,-3]
  
  GC_order <- c("CancerC1","CancerC2","CancerC3","CancerC4","CancerC5","CancerC6","CancerC7","CancerC8","B.cells","T.regs","CD4.T.cells","CD8.T.cells","CD68.MP","CD15.MY","CD11c.MY","CD163.MP","Other.MY","Other.immune","StromalC1","StromalC2","StromalC3","StromalC4","StromalC5","StromalC6","StromalC7","StromalC8")
  
  cells_percentages$GlobalCellType <- factor(cells_percentages$GlobalCellType, levels=GC_order)
  
  p <- ggplot(cells_percentages, aes(x=rcn_id,y=proportion, fill=GlobalCellType)) +
        geom_bar(stat="identity", color="grey20") + theme_classic() +
        theme(axis.text.x=element_text(size=rel(1.2))) + coord_flip() + 
        xlab("") + ylab("Proportion") +
        scale_fill_manual(values = as.character(paletteer_c("grDevices::rainbow", 27)))
  print(paste0("Saving file in:", paste0(out.folder.name,"RCN_barplot_", method,".png")))
  ggsave(p, file=paste0(out.folder.name,"RCN_barplot_", method,".png"), width = 14, height = 12, units = "cm")
  ggsave(p, file=paste0(out.folder.name,"RCN_barplot_", method,".svg"), width = 14, height = 12, units = "cm")
}
cells_percentages.m <- cells_percentages %>% 
                       pivot_wider(names_from = GlobalCellType, values_from = proportion)

cells_percentages.m <- as.data.frame(cells_percentages.m)
row.names(cells_percentages.m) <- cells_percentages.m[,1]
cells_percentages.m <- cells_percentages.m[,-1]
cells_percentages.m[is.na(cells_percentages.m)] <- 0
cells_percentages.m
```

#Calculating diversity for each RCN
```{r}
#Function for calculating diversity and abundance for each RCN
heatmap.diversity <- function(input.cells, method="NA"){
  cells_percentages <- input.cells %>% 
                          group_by(rcn_id, GlobalCellType) %>% 
                          summarise(n = n()) %>% mutate(count = n)
  cells_percentages <- as.data.frame(cells_percentages)
  cells_percentages <- cells_percentages[,-3]
  
  cells_percentages.m <- cells_percentages %>% 
                         pivot_wider(names_from = GlobalCellType, values_from = count)
  
  cells_percentages.m <- as.data.frame(cells_percentages.m)
  row.names(cells_percentages.m) <- cells_percentages.m[,1]
  cells_percentages.m <- cells_percentages.m[,-1]
  cells_percentages.m[is.na(cells_percentages.m)] <- 0

  H <- rev(diversity(cells_percentages.m))
  cluster_abundances <- as.vector(rev(table(input.cells$rcn_id)))
  
  
  col_fun = colorRamp2(c(min(H), max(H)), c("pink", "darkred"))
  
  Rowann <- rowAnnotation(Diversity=H, col = list(Diversity = col_fun),
                          cells = anno_barplot(cluster_abundances))
  
  ht <- Heatmap(matrix(rnorm(l * 3), l), left_annotation = Rowann, cluster_rows = FALSE)
  
  svg(paste0(out.folder.name,"Diversity_RCN_heatmap_", method, ".svg"), width = 6, height = 5.4)
  draw(ht)
  dev.off()
}
```



#Calculating diversity for each RCN
```{r}
#Calculating diversity for each RCN

cells_percentages <- cells %>% group_by(patient, rcn_id) %>% summarise(n = n()) %>% mutate(proportion = n * 100 / sum(n))
cells_percentages <- as.data.frame(cells_percentages)
cells_percentages <- cells_percentages[,-3]

cells_percentages.m <- cells_percentages %>% pivot_wider(names_from = rcn_id, values_from = proportion)

cells_percentages.m <- as.data.frame(cells_percentages.m)
row.names(cells_percentages.m) <- cells_percentages.m[,1]
cells_percentages.m <- cells_percentages.m[,-1]
cells_percentages.m[is.na(cells_percentages.m)] <- 0
cells_percentages.m
cells_percentages.scaled <- scale(cells_percentages.m)


#Getting molecular profile of patients using same order as matrix
Profiles.m <- sapply(row.names(cells_percentages.m), function(x) {
  clindata.shrd[which(clindata.shrd$patient == x)[1],"Molecular.profile2"] })
Profiles.m <- factor(Profiles.m, levels=c("HRD", "BRCAmut/met","BRCAness-sHRD+","BRCAness+sHRD-","CCNE1amp","HRP","Other"))

#Getting therapy sequence of patients using same order as matrix
therapy <- sapply(row.names(cells_percentages.m), function(x) {
  clin.tcycif[which(clin.tcycif$patient == x)[1],"therapy_sequence"] })
therapy[which(therapy == "PDS followed by NACT")] <- "PDS"
therapy[which(therapy == "Primairy debulking")] <- "PDS"
therapy[which(therapy == "Only debulking")] <- "PDS"
therapy[which(therapy == "NACT followed by re-debulking")] <- "NACT"

colours <- list(Therapy=c("NACT"="black", "PDS"="grey90"),
                M.profile=c("BRCAmut/met" = "#ff0000", "HRD" = "#960018", "CCNE1amp"="darkblue", "HRP"="#1E90FF", "BRCAness+sHRD-"="pink", "BRCAness-sHRD+"="#e0115f",  "Other"="grey60"))

ha = rowAnnotation(Therapy=therapy, M.profile=Profiles.m, col =colours)

set.seed(123)
col_c <- colorRamp2(c(-1.5, 0, 2, 4), c("#0000FF","grey95", "#F9AAAA", "#EE0000"))
hmap1 <- Heatmap(cells_percentages.scaled, name="Subtype %\nper patient (Z-score)",
                row_names_gp = gpar(fontsize = 2), column_names_gp = gpar(fontsize = 7), row_title = NULL, column_title = NULL,
                row_names_side = "left", row_dend_side = "right",
                col=col_c, row_km = 3, column_km = 4,
                right_annotation = ha, column_names_rot = 60)
png(paste0(out.folder.name, "RCN_all-heatmap.png"), res=300, width=5, height=7, units = "in")
draw(hmap1)
dev.off()
```

#Heatmap for all cells, dividing by therapy
```{r}
#Heatmap for all cells, dividing by therapy
therapies.vals <- c("NACT","PDS")
for (t in therapies.vals){
  cells_percentages.sel <- cells_percentages.m[which(therapy == t),]
  cells_percentages.sel.scaled <- scale(cells_percentages.sel)

  ha = rowAnnotation(M.profile=Profiles.m[which(therapy == t)], col=colours)
  
  set.seed(321)
  col_c <- colorRamp2(c(-1.5, 0, 2, 4), c("#0000FF","grey95", "#F9AAAA", "#EE0000"))
  hmap1 <- Heatmap(cells_percentages.sel.scaled, name="Subtype %\nper patient (Z-score)",
                  row_names_gp = gpar(fontsize = 3), column_names_gp = gpar(fontsize = 7), column_title = t, row_title = NULL,
                  row_names_side = "left", row_dend_side = "right",
                  col=col_c, #row_km = 3, column_km = 3,
                  right_annotation = ha, column_names_rot = 60)
  
  png(paste0(out.folder.name, t, "_RCN_heatmap.png"), res=300, width=5, height=7, units = "in")
  draw(hmap1)
  dev.off()
}
```





