---
title: "Clinical data intersection"
output: html_notebook
---


```{r}
library(dplyr)
library(tidyverse)
library(survival)
library(survminer)
library(gridExtra)
```


#Reading clinical info
```{r}
#Reading file that matches the tCycif core IDs with samples IDs
cycif2samples <- read.table(file="D:/users/fperez/NKI_TMAs_AF/Clinical_intersection/All-slides_cycif2samples.txt",
                            sep="\t", header = TRUE)

#Clinical info
clinical.info <- read.table(file="D:/users/fperez/NKI_TMAs_AF/Clinical_data/T-CycIF.updated.csv", sep=",", header = TRUE)

clin.tcycif <- merge(cycif2samples, clinical.info, by.x="patient", by.y="TnumberAVL", all.x = TRUE)

#Loading shallowHRD results
shallowHRDresults <- read.table(file="D:/users/fperez/NKI_TMAs_AF/shallowHRDinspection/shallowHRD_summary_table.csv",
                                header=TRUE, sep=",")

#shallowHRD results IDs
IDs <- read.table(file="D:/users/fperez/NKI_TMAs_AF/shallowHRDinspection/sample_names_sWGS.csv", sep=",",
                  header=TRUE)
```


```{r}
clin.pat <- merge(cycif2samples, clinical.info, by.x="patient", by.y="TnumberAVL")

median(clin.pat$refage)
IQR(clin.pat$refage)
```



#Merging clinical info with shallowHRD 
```{r}
colnames(shallowHRDresults)[3] <- "ShallowHRDcall"

#Merging shallowHRD results with clinical data and samples IDs
IDs$CF.ID.number <- as.numeric(sub("X","", IDs$CF.ID.number))
clindata.swgs <- merge(clin.tcycif, IDs, by.x="CFsample", by.y="Description", all.x = TRUE)
clindata.shrd <- merge(clindata.swgs, shallowHRDresults, by.x="CF.ID.number", by.y="Sample", all.x = TRUE)

#Enlisting patients with no clinical information
clindata.shrd %>% filter(patient != "OC liver") %>% 
                select(patient, BRCA_methylation, BRCA_mutation, BRCAness_ovarium, QC_BRCA_CCNE, timelastfu) %>%
                unique() %>% 
                filter(is.na(BRCA_methylation))

#List of patients with no shallowHRD and not BRCAloss
#List of patients with a bad QC (QC==1), these are also considered as Others
clindata.shrd %>% filter(patient != "OC liver") %>% 
              select(patient, BRCA_methylation, BRCA_mutation, BRCAness_ovarium, QC_BRCA_CCNE, ShallowHRDcall) %>%
              unique() %>% 
              filter(!is.na(BRCA_methylation)) %>% 
              filter(!(BRCA_methylation == "BRCA hypermethylation" |
                      grepl("BRCA",BRCA_mutation))) %>% 
              filter(is.na(ShallowHRDcall) | QC_BRCA_CCNE == 1)
```


#Creating new Molecular marker based on shallow HRD, CCNE1amp and BRCAness profile
```{r}
#List BRCAmut/met samples
BRCAsamples <- clindata.shrd[which(clindata.shrd$BRCA_methylation == "BRCA hypermethylation" | grepl("BRCA", clindata.shrd$BRCA_mutation)),"patient"]

CCNE1amp <- clindata.shrd[which(clindata.shrd$CCNE1_revised == "Amplification"), "patient"]

#List of HRD and HRP samples according to shallowHRD
HRDshallow <- clindata.shrd[which(clindata.shrd$ShallowHRDcall == "positive"),"patient"]
HRPshallow <- clindata.shrd[which(clindata.shrd$ShallowHRDcall == "borderline" | clindata.shrd$ShallowHRDcall == "negative"),"patient"]

#List of BRCAnessPos and BRCAnessNeg samples
BRCAnessPos <- clindata.shrd[which(clindata.shrd$BRCAness_ovarium == "BRCAness mutation"),"patient"]
BRCAnessNeg <- clindata.shrd[which(clindata.shrd$BRCAness_ovarium == "No BRCAness mutation"),"patient"]

#Creating column Molecular.profile2, to store the merged of molecular profiles
clindata.shrd$Molecular.profile2 <- rep("Other",  nrow(clindata.shrd))

#Defining HRP in Molecular.profile2
clindata.shrd[which(clindata.shrd$patient %in% HRPshallow & clindata.shrd$patient %in% BRCAnessNeg), "Molecular.profile2"] <- "HRP"

#Defining CCNE1amp in Molecular.profile2
clindata.shrd[which(clindata.shrd$patient %in% CCNE1amp), "Molecular.profile2"] <- "CCNE1amp"

#Defining HRD in Molecular.profile2
clindata.shrd[which(clindata.shrd$patient %in% HRDshallow & clindata.shrd$patient %in% BRCAnessPos), "Molecular.profile2"] <- "HRD"
clindata.shrd[which(clindata.shrd$QC_BRCA_CCNE == 1), "Molecular.profile2"] <- "Other"
clindata.shrd[which(clindata.shrd$patient %in% BRCAsamples), "Molecular.profile2"] <- "BRCAmut/met"

clindata.shrd$imageid <- paste0(clindata.shrd$cycif.slide, "_", clindata.shrd$cycif.core.id)

colmns.interest <- c("Molecular.profile2", "patient","figo_stage","therapy_sequence","finalstatus",
                "timelastfu","daystoprogression","progression","refage","resdx")
clindata.shrd.patient <- unique(clindata.shrd[,colmns.interest])

Molecular.profiles.new <- clindata.shrd.patient %>% select(patient, Molecular.profile2, therapy_sequence)
write.table(Molecular.profiles.new,
             file="D:/users/fperez/NKI_TMAs_AF/Tables/Molecular_profiles_patients_20231208.csv",
             sep=",", row.names=FALSE)
```

# Writing resultant file used in subsequent analysis
```{r}
colmns.interest <- c("cycif.slide", "cycif.core.id", "patient", "Molecular.profile2",
                     "figo_stage","therapy_sequence","finalstatus",
                      "timelastfu","daystoprogression","progression")
clindata.shrd.cores <- unique(clindata.shrd[,colmns.interest])
write.table(clindata.shrd.cores,
             file="D:/users/fperez/NKI_TMAs_AF/Tables/Molecular_profiles_cores_20230314.csv",
             sep=",", row.names=FALSE)

```

#Generating survival plots for patients according to their group
```{r}
out.folder.name <- "D:/users/fperez/NKI_TMAs_AF/Analysis_results/00_Survival_molecular_profiles/"


clin.dat = clindata.shrd.patient[clindata.shrd.patient$patient != "OC liver",]

#Structuring data for stage as continuous variable
clin.dat$Stage <- NA
clin.dat$Stage[clin.dat$figo_stage == "FIGO II"] <- 2
clin.dat$Stage[clin.dat$figo_stage == "FIGO III"] <- 3
clin.dat$Stage[clin.dat$figo_stage == "FIGO IV"] <- 4

#Structuring Age in groups
clin.dat$Age <- NA
clin.dat$Age[clin.dat$refage < 50] <- 0
clin.dat$Age[clin.dat$refage >= 50 & clin.dat$refage < 60] <- 1
clin.dat$Age[clin.dat$refage >= 60 & clin.dat$refage < 70] <- 2
clin.dat$Age[clin.dat$refage >= 70 & clin.dat$refage < 80] <- 3
clin.dat$Age[clin.dat$refage >= 80] <- 4


#Changing time to months
clin.dat$Time <- (clin.dat$timelastfu) / 30.4
clin.dat$daystoprogression <- (clin.dat$daystoprogression) / 30.4

clin.dat$Therapy <- ifelse(grepl("NACT", clin.dat$therapy_sequence), "IDS","PDS")
clin.dat$Therapy[which(is.na(clin.dat$therapy_sequence))] <- NA

#Structuring molecular profiles
clin.dat$Molecular.profile <- clin.dat$Molecular.profile2
clin.dat$Molecular.profile[clin.dat$Molecular.profile == "BRCAmut/met"] <- "BRCAloss"
clin.dat$Molecular.profile <- factor(clin.dat$Molecular.profile,
                                     levels=c("HRP", "BRCAloss","CCNE1amp","HRD","Other"))


formulas.cox <- c('Surv(Time, finalstatus) ~  Age + Stage + Molecular.profile',
              'Surv(daystoprogression, progression)~ Age + Stage + Molecular.profile')

formulas.kapplan <- c('Surv(Time, finalstatus) ~  Molecular.profile2',
              'Surv(daystoprogression, progression)~ Molecular.profile2')


formulas.names <- c("OS","PFI")
formulas.labs <- c("OS probability","PFI probability")

therapies <- c("IDS","PDS")

#Generating a Kaplan–Meier plot per each therapy sequence
for (t in therapies){
  df <- clin.dat
  df <- df %>% filter(Therapy == {t})
  
  for (i in 1:length(formulas.kapplan)){
     #Cox model 
     cox.model <- coxph(as.formula(formulas.cox[i]), data=df)
     p1 <- ggforest(cox.model, data = df, main=paste0(formulas.labs[i]," ", t))
     print(p1)
     ggsave(p1, file=paste0(out.folder.name, "Cox_",t, "_", formulas.names[i],".png"),
           width = 14, height = 7, units = "cm")
     ggsave(p1, file=paste0(out.folder.name, "Cox_",t, "_", formulas.names[i],".svg"),
           width = 14, height = 7, units = "cm")
     
     #Kapplan-Meir
     fit <- survfit(as.formula(formulas.kapplan[i]), data = df)
     logrank = surv_pvalue(fit, clin.dat)
     pval=logrank$pval.txt
     
     #Kapplan-Meir
     p <- ggsurvplot(fit, data = df, risk.table = TRUE, pval=FALSE,
                        #conf.int = TRUE, palette = c("#4d4dff", "#ff5a36"),
                       legend.labs=c("BRCAloss","CCNE1amp","HRD","HRP","Other"),
                        tables.y.text = FALSE, legend.title="",
                       break.time.by=30,
                     ylab=formulas.labs[i]) 
     p$plot <- p$plot + guides(colour = guide_legend(nrow = 2))
     p$plot <- p$plot + theme(legend.key.width = unit(3, "line"),
                                  plot.margin = margin(t = 0,  r = 2, b = 0, l = 1.5, unit = "cm"),
                                  legend.key.height = unit(1.5, "line"))
     p$plot <- p$plot + ggplot2::annotate("text", x = 75, y = 0.85, label =pval, size = 5)
     p$table <- p$table + theme(plot.margin = margin(t = 0,  r = 2, b = 5, l = 2, unit = "cm"))
     plot.to.save <- list(p$plot, p$table)
     ggsave(file=paste0(out.folder.name,"Kapplan_",t, "_", formulas.names[i],".png"),
           arrangeGrob(grobs = plot.to.save, ncol = 1),
         width = 13, height = 19, units = "cm")
  }
}

formulas.cox <- c('Surv(Time, finalstatus) ~  Age + Stage + Therapy +  Molecular.profile',
              'Surv(daystoprogression, progression)~ Age + Stage +  Therapy + Molecular.profile')

for (i in 1:length(formulas.kapplan)){
   cox.model <- coxph(as.formula(formulas.cox[i]), data=clin.dat)
   p1 <- ggforest(cox.model, data = clin.dat, main=paste0(formulas.labs[i]," full cohort"))
   print(p1)
   ggsave(p1, file=paste0(out.folder.name, "Cox_Both_", formulas.names[i],".png"),
         width = 12, height = 8.5, units = "cm")
   ggsave(p1, file=paste0(out.folder.name, "Cox_Both_", formulas.names[i],".svg"),
         width = 12, height = 8.5, units = "cm")
  
  #Kapplan-Meir
  fit <- survfit(as.formula(formulas.kapplan[i]), data = clin.dat)
  logrank = surv_pvalue(fit, clin.dat)
  pval=logrank$pval.txt
  
  p <- ggsurvplot(fit, data = clin.dat, risk.table = TRUE, pval=FALSE,
                    #conf.int = TRUE, palette = c("#4d4dff", "#ff5a36"),
                   legend.labs=c("BRCAloss","CCNE1amp","HRD","HRP","Other"),
                    tables.y.text = FALSE, legend.title="",
                   break.time.by=30,
                 ylab=formulas.labs[i])
  p$plot <- p$plot + guides(colour = guide_legend(nrow = 2))
  p$plot <- p$plot + ggplot2::annotate("text", x = 75, y = 0.85, label =pval, size = 5)
  p$plot <- p$plot + theme(legend.key.width = unit(3, "line"),
                                  plot.margin = margin(t = 0,  r = 2, b = 0, l = 1.5, unit = "cm"),
                                  legend.key.height = unit(1.5, "line"))
  p$table <- p$table + theme(plot.margin = margin(t = 0,  r = 2, b = 5, l = 2, unit = "cm"))
  
  plot.to.save <- list(p$plot, p$table)
  ggsave(file=paste0(out.folder.name,"Kapplan_Both_", formulas.names[i],".png"),
           arrangeGrob(grobs = plot.to.save, ncol = 1),
         width = 13, height = 19, units = "cm")
  ggsave(file=paste0(out.folder.name,"Kapplan_Both_", formulas.names[i],".svg"),
         arrangeGrob(grobs = plot.to.save, ncol = 1),
       width = 13, height = 19, units = "cm")
}
```

